name: Dizi Botu Güncelleyici

on:
  schedule:
    # Her gün saat 00:00 ve 12:00'da (UTC) çalışır
    - cron: '0 0,12 * * *'
  workflow_dispatch: # Manuel çalıştırma butonu

permissions:
  contents: write

jobs:
  update-movies:
    runs-on: ubuntu-latest

   steps:
    - name: Depoyu Cek
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # SeleniumBase 3.10 ile daha iyi çalışır

    - name: Gerekli Paketleri Kur (Chrome ve Xvfb)
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb google-chrome-stable
        pip install seleniumbase beautifulsoup4
        # SeleniumBase için sürücüyü indir
        seleniumbase install chromedriver

    - name: Botu Calistir (Sanal Ekran Modunda)
      env:
        SITE_URL: 'https://dizipal.cx/diziler'
      # xvfb-run komutu, tarayıcıyı sanki gerçek bir ekran varmış gibi çalıştırır (Bot korumasını aşar)
      run: xvfb-run python main2.py

    - name: Degisiklikleri Kaydet ve Yukle
      run: |
        git config --global user.name "Dizi Botu"
        git config --global user.email "bot@github.com"
        git add .
        git commit -m "Otomatik guncelleme" || echo "Degisiklik yok"
        git pull --rebase origin main
        git push origin main
